[package]
name = "complex_newton"
version = "0.1.0"
edition = "2021"
description = "newton's method for finding solutions of complex equations"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
