[package]
name = "bbp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.24.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "bbp"
harness = false
