[package]
name = "polyzero"
description = "find the roots of a polynomial recursively via Newton's method on radii of its derivative's zeros"
license = "MIT"
version = "0.0.1"
edition = "2021"

[dependencies]
itertools = "0.11.0"
num-complex = "0.4.4"
num-traits = "0.2.17"
rayon = "1.8.0"
